"""empty message

Revision ID: 55a9c2befe2c
Revises: 87f23f187b5a
Create Date: 2020-06-05 11:35:05.628743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55a9c2befe2c'
down_revision = '87f23f187b5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###
