"""empty message

Revision ID: a0721d9e8dee
Revises: 55a9c2befe2c
Create Date: 2020-06-05 11:36:49.673871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0721d9e8dee'
down_revision = '55a9c2befe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_student_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_student_id_fkey', 'user', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###
